name: MLflow-UC OSS Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

env:
  MLFLOW_HOME: /home/runner/work/mlflow/mlflow
  UC_OSS_INTEGRATION: true

jobs:
  uc-oss-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions: {}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install mlflow
          pip install pytest
      - name: Start uc-oss server
        run: |
          build/sbt package
          nohup bin/start-uc-server > uc-server.log 2>&1 &

      - name: Run tests for UnityCatalog
        run: |
          echo "Running tests for UnityCatalog..."
          export PYTHONPATH=$MLFLOW_HOME:$PYTHONPATH
          pytest tests/test_mlflow_integration.py
